# Generated by Django 3.1 on 2020-09-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='describe',
        ),
        migrations.RemoveField(
            model_name='book',
            name='email',
        ),
        migrations.RemoveField(
            model_name='book',
            name='picture',
        ),
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='copies',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=123456789111, max_length=12),
            preserve_default=False,
        ),
    ]
