# Generated by Django 3.1 on 2020-09-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200914_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('e', 'English'), ('m', 'Marathi'), ('h', 'Hindi')], default='e', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='anonymos', max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1),
        ),
    ]
