# Generated by Django 3.1 on 2020-09-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200919_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Marathi', 'Marathi'), ('Hindi', 'Hindi')], max_length=7),
        ),
    ]
