# Generated by Django 3.1.1 on 2020-09-19 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20200919_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('assign_date', models.DateField(verbose_name='book assign')),
                ('due_date', models.DateField(verbose_name='Due on')),
                ('fine', models.IntegerField()),
                ('book_assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
    ]
