# Generated by Django 3.1 on 2020-09-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20200919_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('IT', 'IT'), ('CSE', 'CSE'), ('MECH', 'MECH'), ('PROD', 'PROD'), ('CHEM', 'CHEM'), ('CIVIL', 'CIVIL'), ('TEXT', 'TEXT'), ('EXTC', 'EXTC'), ('ELECT', 'ELECT'), ('INSTRU', 'INSTRU')], default='IT', max_length=6),
        ),
        migrations.AddField(
            model_name='student',
            name='reg_no',
            field=models.CharField(default='**********', max_length=10),
        ),
    ]
